import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import { MyProvider } from "@/context/DynamicContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BKMower",
  description: "Generated by create next app",
};

// Dynamically import Navbar and Footer
const Navbar = dynamic(() => import("@/app/components/global/header/Navbar"));
const Footer = dynamic(() => import("@/app/components/global/footer/Footer"));

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <MyProvider>
          <Navbar />
          {children}
          <Footer />
        </MyProvider>
      </body>
    </html>
  );
}